# Generated by Django 5.2.8 on 2025-11-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='created_at',
            new_name='posted_at',
        ),
    ]
