# Generated by Django 5.2.8 on 2025-11-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_created_at_jobposting_posted_at'),
        ('skills', '0002_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='external_url',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='required_skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs_requiring', to='skills.skill'),
        ),
    ]
