# Generated by Django 5.2.8 on 2025-11-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobposting_external_url_and_more'),
        ('skills', '0002_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='jobs_requiring', to='skills.skill'),
        ),
    ]
