# Generated by Django 5.2.8 on 2025-11-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobposting_required_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-posted_at']},
        ),
    ]
