# base URL
@baseUrl = http://127.0.0.1:8000/api
@authTokenRecruiter = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzcxMTk4LCJpYXQiOjE3NjQzNjc1OTgsImp0aSI6ImFkOGIyN2M0OGFlOTQxOTY4NTMyMzFiZmQ5NGI3YzExIiwidXNlcl9pZCI6IjQxM2YzYzk0LWYxMWYtNDY3ZS1iOTBlLTcxMjcwZjY0M2I4NyJ9.VHMBNOrtkKpVfM6VaiE3lSVxXVLiTjzaGC2K6_CgBEc
@authTokenCandidate = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzcxMjM0LCJpYXQiOjE3NjQzNjc2MzQsImp0aSI6ImViYjYzOTZjYWM4NzQxMWY5NDk2ZjI2MmRiY2Y1YzE0IiwidXNlcl9pZCI6ImRmN2VhYzZlLTVlZWYtNDY5NC1iZDA0LWQxMTY1YTIzOTJhYSJ9.5MQa-VtyDw4eLuVczQbLyNvqkdcfljbwMcPeOmgF0Wo
###
POST {{baseUrl}}/users/register/
Content-Type: application/json

{
    "email": "recruiter4@gmail.com",
    "password": "recruiter4",
    "role": "recruiter"
}

###
POST {{baseUrl}}/users/register/
Content-Type: application/json

{
    "email": "candidate2@gmail.com",
    "password": "candidate2"
}
###
POST {{baseUrl}}/auth/login/
Content-Type: application/json

{
    "email": "recruiter4@gmail.com",
    "password": "recruiter4"
}

###
POST {{baseUrl}}/auth/login/
Content-Type: application/json

{
    "email": "candidate2@gmail.com",
    "password": "candidate2"
}

###
GET {{baseUrl}}/users/me/
Authorization: Bearer {{authTokenRecruiter}}

###
GET {{baseUrl}}/profile/candidate/
Authorization: Bearer {{authTokenCandidate}}

###
PUT {{baseUrl}}/profile/candidate/
Authorization: Bearer {{authTokenCandidate}}
content-type: application/json

{
        "skills_ids": ["bf689c35-556f-414e-af6c-bd51891857a2", "07215bf4-aa18-426b-b8eb-6e8a0c3777fb"],
        "bio": "Experienced software developer with a passion for creating innovative solutions."
}

###
DELETE  {{baseUrl}}/profile/candidate/
Authorization: Bearer {{authTokenCandidate}}
content-type: application/json

###
GET {{baseUrl}}/companies/

###
GET {{baseUrl}}/companies/my/
Authorization: Bearer {{authTokenRecruiter}}

###
POST {{baseUrl}}/companies/
Authorization: Bearer {{authTokenRecruiter}}
content-type: application/json

{
    "name": "Majimaji Tech Corp",
    "description": "A leading tech company specializing in software development.",
    "location": "San Francisco, CA"
}

###
GET {{baseUrl}}/companies/bcda38c6-eff0-4f44-b4b7-97e487149c03/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNTMzNTA4LCJpYXQiOjE3NjM1MzMyMDgsImp0aSI6ImE5ZDM1YzEzNWZhYTRlOTE5ZmE3OTA5ZjNjMDAxM2YzIiwidXNlcl9pZCI6ImE1ZGM0NmJjLTY1NWQtNGI0ZS05NDJjLWE0MThlYWZjNDdiOSJ9.3GMcSQnia06kKK9VvmQ8Ln6KoC5q39YE0KoeT2Zx5n0

###
PUT {{baseUrl}}/companies/bcda38c6-eff0-4f44-b4b7-97e487149c03/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNTMzODM0LCJpYXQiOjE3NjM1MzM1MzQsImp0aSI6ImE1OTQxMTFlODYwNDRiOTliMmMwNzA5YzAwMGFjMjliIiwidXNlcl9pZCI6ImE1ZGM0NmJjLTY1NWQtNGI0ZS05NDJjLWE0MThlYWZjNDdiOSJ9.aiI87E4n8fM5IeltZYpb0wprL15AEUobQIFQ9zgKH5w
Content-Type: application/json

{
    "name": "Tech Solutions International",
    "description": "An innovative tech company focusing on AI and ML solutions.",
    "location": "New York, NY"
}

###
DELETE {{baseUrl}}/companies/bcda38c6-eff0-4f44-b4b7-97e487149c03/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNTMzODM0LCJpYXQiOjE3NjM1MzM1MzQsImp0aSI6ImE1OTQxMTFlODYwNDRiOTliMmMwNzA5YzAwMGFjMjliIiwidXNlcl9pZCI6ImE1ZGM0NmJjLTY1NWQtNGI0ZS05NDJjLWE0MThlYWZjNDdiOSJ9.aiI87E4n8fM5IeltZYpb0wprL15AEUobQIFQ9zgKH5w

###
GET {{baseUrl}}/skills/

###
POST {{baseUrl}}/skills/
Content-Type: application/json

{
    "name": "C++"
}
###
DELETE {{baseUrl}}/skills/d763ecbe-7872-4ebd-a704-1d9689261762/

###
GET {{baseUrl}}/jobs/?title=Engineer

###
POST {{baseUrl}}/jobs/
Content-Type: application/json
Authorization: Bearer {{authTokenRecruiter}}

{
    "title": "Senior Backend Engineer",
    "description": "Responsible for server-side web application logic and integration.",
    "location": "Remote",
    "is_external": false,
    "external_url": "",
    "company": "829cd57f-9064-4223-b0ba-368f9c2388d6"
}

###
GET {{baseUrl}}/jobs/c91752f9-1331-4ad2-a29c-3182faa8f133/

###
PUT {{baseUrl}}/jobs/33557d79-6914-412f-9b71-31e4df4fe665/
Content-Type: application/json
Authorization: Bearer {{authTokenRecruiter}}

{
    "title": "Senior Backend Engineer",
    "description": "Responsible for server-side web application logic and integration. Must have experience with microservices.",
    "required_skills": ["bf689c35-556f-414e-af6c-bd51891857a2", "07215bf4-aa18-426b-b8eb-6e8a0c3777fb"]
}

###
POST {{baseUrl}}/jobs/33557d79-6914-412f-9b71-31e4df4fe665/apply/
Authorization: Bearer {{authTokenCandidate}}

###
GET {{baseUrl}}/jobs/33557d79-6914-412f-9b71-31e4df4fe665/applicants/
Authorization: Bearer {{authTokenRecruiter}}

###
GET {{baseUrl}}/applications/my/
Authorization: Bearer {{authTokenCandidate}}